### ISSUE TITLE
FFMpeg path on linux

### ISSUE THREAD

**Issue by Bassist067** [mysteryx93/HanumanInstitute.FFmpeg#1]
Hi! Thanks for the real nice library here - it works surprisingly fast. How can I run this on ubuntu server? If I install ffmpeg via apt-get, I receive the following:

System.IO.FileNotFoundException: The file "usr/bin/ffmpeg" for the encoding application FFmpeg configured in MediaConfig was not found.
File name: 'usr/bin/ffmpeg'
   at EmergenceGuardian.Encoder.ProcessWorkerEncoder.RunEncoder(String arguments, String encoderApp)
   at EmergenceGuardian.Encoder.ProcessWorkerEncoder.RunEncoder(String arguments, EncoderApp encoderApp)
   at EmergenceGuardian.Encoder.MediaMuxer.Concatenate(IEnumerable`1 files, String destination, ProcessOptionsEncoder options, ProcessStartedEventHandler callback)

Is the Encoder designed as Windows-only?

**Comment by mysteryx93** [comment]
I don't know where Ubuntu installs it by default. Find the path where FFMPEG got installed and you need to set that path in MediaConfig.FFmpegPath. I haven't tried it on Linux but it should work. Let me know if you encounter any issues.

**Comment by mysteryx93** [comment]
I'm currently modernizing the code and making it cross-platform-compatible.

Main library and all tests are working now; just remains to rewrite/update the ExampleApplication cross-platform.
